name: Build and Deploy .NET Web App

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: dotnet-webapp-demo
  AZURE_WEBAPP_PACKAGE_PATH: './app/'

jobs:
  build-and-test:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET``
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run:  dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      
    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
  
  deploy:
    needs: build-and-test
  
    runs-on: [ self-hosted ]
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
    - name: Download Production Artifacts
      uses: actions/download-artifact@v3
      with:
        name: package
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
    - name: Deploy to Azure Web Apps
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
